name: 'Setup'
description: 'Prepare Pnpm and Node.js environment'

runs:
  using: composite
  steps:
    - name: Setup Node.js and Pnpm
      uses: actions/setup-node@v4
      with:
        node-version-file: [18.x, 20.x, 22.x]
        registry-url: 'https://registry.npmjs.org'
        cache: 'pnpm'
    - name: Install Dependencies
      shell: bash
      run: pnpm install
