name: 'Setup'
description: 'Prepare Pnpm and Node.js environment'

runs:
  using: composite

  strategy:
    matrix:
      node-version: [18.x, 20.x, 22.x]

  steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Install Dependencies
      shell: bash
      run: pnpm install
