name: Continuous Integration (Before merge to "development" branch)

on:
  pull_request:
    branches: ['development', 'production']

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
    # - name: Build
    #   run: npm run build

  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Run Tests
        run: npm run test

  svlete-check:
    name: Svelte Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Run npm Check
        run: npm run check

  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Run ESLint
        run: npm run lint

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Run Prettier
        run: npm run prettier:format

  generate-css:
    name: Generate CSS & Commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      # TODO: Generate global.css files 
      - name: Generate global CSS for UI components
        run: npm run tailwind-comp
      - name: Generate global CSS for Documentation
        run: npm run tailwind-doc
      # TODO: Generate global.css files 
      - name: Add and Commit
        uses: EndBug/add-and-commit@v9
        with:
          message: Updated global CSS files
          committer_name: GitHub Actions
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com

