# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Continuous Integration (Before merge to "development" branch)

on:
  push:
    branches: ['development']
  pull_request:
    branches: ['development']

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/setup
    # - name: Build
    #   run: pnpm run build

  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/setup
      - name: Run Tests
        run: pnpm install

  svlete-check:
    name: Svelte Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/setup
      - name: Run Pnpm Check
        run: pnpm run check

  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/setup
      - name: Run ESLint
        run: pnpm run lint

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/setup
      - name: Run Prettier
        run: pnpm run prettier:format
