name: Continuous Integration (Before merge to "development" branch)

on:
  pull_request:
    branches: ['development', 'production']

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
    # - name: Build
    #   run: npm run build

  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Run Tests
        run: npm run test

  svlete-check:
    name: Svelte Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Run npm Check
        run: npm run check

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Run Prettier
        run: npm run prettier:format

  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Run ESLint
        run: npm run eslint
