name: Continuous Integration (Before merge to "development" branch)

on:
  pull_request:
    branches: ['development', 'production']

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
    # - name: Build
    #   run: npm run build

  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Run Tests
        run: npm run test

  # TODO: Generate global.css files 
  generate-css:
    name: Generate CSS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Generate global CSS for UI components
        run: npm run tailwind-comp
      - name: Generate global CSS for Documentation
        run: npm run tailwind-doc

  svlete-check:
    name: Svelte Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Run npm Check
        run: npm run check

  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Run ESLint
        run: npm run lint

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Run Prettier
        run: npm run prettier:format

  # TODO: Commit global.css files to the repo
  commit:
    name: Commit Global CSS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Commit Global CSS
        run: git add -A && git commit -m "chore: update global css" && git push
