# name: Continuous Integration (Before merge to "development" branch)

# on:
#   push:
#     branches: ['development']
#   pull_request:
#     branches: ['development']

# jobs:
#   build:
#     name: Build
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Repo
#         uses: actions/checkout@v4
#       - name: Setup
#         uses: ./.github/actions/setup
#     # - name: Build
#     #   run: npm run build

#   test:
#     name: Tests
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Repo
#         uses: actions/checkout@v4
#       - name: Setup
#         uses: ./.github/actions/setup
#       - name: Run Tests
#         run: npm install

#   svlete-check:
#     name: Svelte Check
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Repo
#         uses: actions/checkout@v4
#       - name: Setup
#         uses: ./.github/actions/setup
#       - name: Run npm Check
#         run: npm run check

#   eslint:
#     name: ESLint
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Repo
#         uses: actions/checkout@v4
#       - name: Setup
#         uses: ./.github/actions/setup
#       - name: Run ESLint
#         run: npm run lint

#   prettier:
#     name: Prettier
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Repo
#         uses: actions/checkout@v4
#       - name: Setup
#         uses: ./.github/actions/setup
#       - name: Run Prettier
#         run: npm run prettier:format

name: Node.js CI

on:
  push:
    branches: ['development']
  pull_request:
    branches: ['development']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install
      - run: npm run test
